### ISSUE TITLE
Works but maybe you could enhance README file

### ISSUE THREAD

**Issue by metal3d** [icewind/ltex-client.nvim#3]
Hello and, at first, thanks for this nice plugin.

I spent a few time to understand why the plugin didn't work (no command and add to dictionary failed).

I agree that you mentioned to call the `setup()` function, but it's a bit confused with LazyVim.

Actually, to ensure that LazyVim calls the setup function, you need to pass the `opts` as non-null content (it could be empty).

So, on my side:

```lua
return {
  {
    "icewind/ltex-client.nvim",
    opts = {},
  },
}
```

To ensure that Mason includes `ltex-ls` it's also possible to give:

```lua
return {
  -- ensure mason istalls ltex-ls
  {
    "williamboman/mason.nvim",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, { "ltex-ls" })
    end,
  },
  {
    "icewind/ltex-client.nvim",
    opts = {},
  },
}
```

It works

**Comment by icewind** [comment]
Hello, thank you for your feedback. To my understanding, we can use `config = true` to make lazy.nvim automatically call setup function. At least it works in my setup that way. 
I've updated the README, please feel free to comment if there is something I can add to make it more helpful.

**Comment by metal3d** [comment]
Ha maybe I missed the "config" attribute. Right.

I will take a look. Thanks a lot, because having the "add to dictionary" is
a must have, and I didn't had the time to implement it on my side 😁

Le lun. 28 oct. 2024, 19:55, Nikolay Osaulenko ***@***.***> a
écrit :

**Comment by metal3d** [comment]
Hi,
Here: https://lazy.folke.io/developers it is mentioned that we should use `opts` to an empty table.

**Comment by icewind** [comment]
Hello, 
Oh, I see. Thank you. I updated the readme.
